### ISSUE TITLE
getAge() is inconsistent with getDateOfBirth()

### ISSUE THREAD

**Issue by urbanaut** [Devskiller/jfairy#94]
When a person object is instantiated, and then date of birth and age are generated, the age will not match up with birth date year.

**Comment by mariuszs** [comment]
Could you show any example of this bug?

**Comment by jiminhsieh** [comment]
@mariuszs @OlgaMaciaszek 
Could I work on this one?

**Comment by mariuszs** [comment]
Yes!  :)

**Comment by jiminhsieh** [comment]
@mariuszs I think this issue is related to how we calculate age.

Here is the example of the current calculation:
If today is 2020/01/01 and age is 20, then the birth date will between 2000/01/01 to 1999/01/02.

https://github.com/Devskiller/jfairy/blob/126d1c8b1545f725afd10f969b9d27005ac520b7/src/main/java/com/devskiller/jfairy/producer/person/DefaultPersonProvider.java#L196-L198

I think this is legitimate.

@urbanaut Could you elaborate on what you expect? Thanks.

**Comment by kdebski85** [comment]
@mariuszs 
I also checked the calculation and every seems to be fine now.
Maybe we can close this issue.

**Comment by mariuszs** [comment]
Ok, thanks!
